"""TSGAM Model Evaluation

This scripts generates TSGAM model evaluation results on the cluster medoids stored in
`tests/clusters.csv`, which is generated by the script section of `cluster.py.

The following files are generated.

- `tests/best_config.csv` contains the best TSGAM configuration found for each
  medoid county in WECC.

- `tests/check_config.csv` contains the best TSGAM configuration found for up
  to 5 counties in each cluster compared to the medoid configuration for its cluster

- `tests/*.png` contain the actual and predicted values for each medoid county.

"""

import os
import sys
from typing import Tuple
from time import time

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from tsgam_estimator import (
    TsgamEstimatorConfig, 
    TsgamMultiPeriodicConfig,
    TsgamSplineConfig,
    TsgamArConfig,
    TsgamSolverConfig,
    TsgamEstimator,
    )

from loads import Total

def partition_datetime_index_weeks(
    dt_index: pd.DatetimeIndex,
    n_weeks: int = 1,
) -> Tuple[pd.DatetimeIndex, pd.DatetimeIndex]:
    """
    Partition a datetime index into training and test sets.
    
    Holds out N evenly-spaced weeks throughout the year for testing.
    The weeks are distributed to maximize spacing across the year.
    
    Parameters
    ----------
    dt_index : pd.DatetimeIndex
        The datetime index to partition (can be tz-aware or tz-naive)
    n_weeks : int, default=1
        Number of weeks to hold out for testing. These weeks will be
        evenly distributed throughout the year. If n_weeks=1, the last
        week is held out. If n_weeks=2, weeks 26 and 52 are held out, etc.
        
    Returns
    -------
    Tuple[pd.DatetimeIndex, pd.DatetimeIndex]
        A tuple of (training_index, test_index)
        
    Examples
    --------
    >>> idx = pd.date_range('2023-01-01', '2023-12-31', freq='D')
    >>> train_idx, test_idx = partition_datetime_index_weeks(idx, n_weeks=2)
    >>> len(train_idx) + len(test_idx) == len(idx)
    True
    
    Notes
    -----
    - Week numbers are based on ISO 8601 week-numbering year (1-52 or 1-53)
    - For N weeks, the weeks are selected as: 52, 52-52/N, 52-2*52/N, ...
    - This ensures even spacing with the last week always included
    """
    if n_weeks < 1:
        raise ValueError("n_weeks must be at least 1")
    
    if n_weeks > 52:
        raise ValueError("n_weeks cannot exceed 52 (weeks in a year)")
    
    # Calculate which week numbers to hold out
    # We want to evenly space N weeks across 52 weeks, always including week 52
    if n_weeks == 1:
        test_weeks = {52}
    else:
        # Space weeks evenly: 52, 52-52/N, 52-2*52/N, etc.
        spacing = 52 / n_weeks
        test_weeks = set()
        for i in range(n_weeks):
            week_num = int(round(52 - i * spacing))
            # Ensure week number is valid (1-53)
            week_num = max(1, min(53, week_num))
            test_weeks.add(week_num)
    
    # Create boolean mask for test dates
    is_test = pd.Series(False, index=range(len(dt_index)))
    
    for i, dt in enumerate(dt_index):
        # Get ISO week number (1-52 or 1-53)
        week_num = dt.isocalendar()[1]
        
        # Get ISO year (may differ from calendar year for dates near year boundary)
        iso_year = dt.isocalendar()[0]
        
        # Check if this week number is in our test set
        # We need to check for each ISO year separately to handle multi-year indices
        if week_num in test_weeks:
            is_test.iloc[i] = True
    
    test_index = dt_index[is_test.values]
    train_index = dt_index[~is_test.values]
    return train_index,test_index

def predict(
    X:pd.DataFrame,
    y:np.array,
    training:pd.DatetimeIndex,
    year_harmonics:int,
    week_harmonics:int,
    day_harmonics:int,
    n_knots:int,
    lag_size:int,
    *,
    verbose:bool=False,
    random_state:float|None=None,
    debug:bool=False,
    ):
    """Construct estimator from config parameters and predict data"""
    config = TsgamEstimatorConfig(
        multi_periodic_config=TsgamMultiPeriodicConfig(
            num_harmonics=[year_harmonics, week_harmonics, day_harmonics],
            periods=[365.2425 * 24, 7 * 24, 24]
        ),
        exog_config=[TsgamSplineConfig(
                    knots=[],  # Empty list means knots will be auto-generated from data
                    n_knots=n_knots,  # Number of knots to generate
                    lags=list(range(-lag_size,lag_size+1)),
                    reg_weight=1e-4,  # Regularization weight for coefficients
                    diff_reg_weight=1.0  # Regularization weight for differences between lags
                )],
        ar_config=None,
        solver_config=TsgamSolverConfig(
            solver='CLARABEL',
            verbose=verbose
        ),
        random_state=random_state,
        debug=debug
    )

    scale = y.max()
    estimator = TsgamEstimator(config=config)
    estimator.fit(X.loc[training],y.loc[training].values / scale)

    # get the test data
    return estimator.predict(X) * scale

def evaluate(actuals,values,ndx):
    """Evaluate rmse of data columns over specified index"""
    return np.sqrt(((actuals.loc[ndx] - values.loc[ndx])**2).mean())

CACHE = None
def mindir(choices,X,y,training,testing,best=None,result=None,ref=None):
    """Find best training configuration among choices of configuration"""

    found = False
    for choice in choices if best is None else [best]+choices:

        try:
            try:
                rmse,values = CACHE[str(choice)]
            except KeyError:
                tic = time()
                values = pd.DataFrame({"predict":predict(X,y,training,*choice)},index=X.index)
                rmse = evaluate(y,values["predict"],testing).round(2)
                CACHE[str(choice)] = (rmse,values)
                print(*choice,f"{rmse:.2f},{time()-tic:.3f}",flush=True,sep=",")
            if best is None or rmse < ref:
                found = True
                best = choice
                result = values
                ref = rmse
        except Exception as err:
            print("EXCEPTION",err,sep=",")
    if not found:
        raise RuntimeError("already optimal")
    return best,result,ref

def optimize(X,y,training,testing,bounds,best=None):
    """Optimize configuration for X,y given holdout"""

    if best is None:
        best = [min(x) for x in bounds]
    result = pd.DataFrame(
        {"predict":predict(X,y,training,*best)},
        index=data.index,
        )
    rmse = evaluate(y,result["predict"],testing)

    global CACHE
    CACHE={}

    try:
        while True:
            choices = []
            for n,x in enumerate(best):
                if x < max(bounds[n]):
                    nextbest = list(best)
                    nextbest[n] = x+1
                    choices.append(nextbest)
                if x > min(bounds[n]):
                    nextbest = list(best)
                    nextbest[n] = x-1
                    choices.append(nextbest)
            if choices == []:
                break
            choice,values,test = mindir(choices,X,y,training,testing,best,result,rmse)
            if test < rmse:
                best,result,rmse = choice,values,test
    except RuntimeError as err:
        if str(err) != "already optimal":
            raise
    return best,result,rmse

if __name__ == '__main__':

    pd.options.display.max_columns = None
    pd.options.display.width = None
    # pd.options.display.max_rows = None

    k = 6
    exog = ["temperature_degF","humidity_pc"]
    column = "elec_total_MW"

    # you must run cluster.py script to create this file
    clusters = pd.read_csv("tests/clusters.csv",index_col=["k","column"]).sort_index()
    medoids = clusters.loc[(k,column),"medoid"].unique().tolist()
    
    dt_range = pd.date_range("2018-01-01 00:00:00+0000","2018-12-31 23:59:59+0000",freq="1h")
    training,testing = partition_datetime_index_weeks(dt_range,8)
    
    limits = [
        [2,20], # year harmonics
        [2,20], # week harmonics
        [2,20], # day harmonics
        [2,20], # knots
        [0,10], # lag max
        ]

    if not os.path.exists("tests/best_config.csv"):
        with open("tests/test_config.csv","w") as fh:
            print("county,state,nh_year,nh_week,nh_day,n_knots,lags_pm,rmse",file=fh)
            # print("nh_year,nh_week,nh_day,n_knots,lags_pm,rmse_MW,time_s")
            for county in medoids:
                state = county.split(" ")[-1]
                county = " ".join(county.split(" ")[:-1])
                data = Total(state,county)
                X = data[exog]
                y = data[column]
                # print("#",state,county)
                config,data["predict"],rmse = optimize(X,y,training,testing,limits)
                # print("#",*exog,"->",column,":",config)
                print(county,state,*config,rmse,sep=",",file=fh)
                data[[column,"predict"]].plot(
                    title=f"{county} {state} {column} {config} RMSE={rmse:.1f} MW ({rmse/data[column].mean()*100:.1f}%)",
                    figsize=(20,10),
                    grid=True,
                    )
                plt.savefig(f"tests/{county}_{state}.png")

    best_config = pd.read_csv("tests/best_config.csv",index_col=[1,0]).sort_index()
    best_config.index = [f"{y} {x}" for x,y in best_config.index]
    best_config.sort_index(inplace=True)
    print("Best TSGAM Configurations",
          "-------------------------",
          best_config,
          "",sep="\n")

    if not os.path.exists("tests/check_config.csv"):
        with open("tests/check_config.csv","w") as fh:

            sys.stdout = fh
            clusters = pd.read_csv("tests/clusters.csv",index_col=[2,3]).sort_index()
            for county in best_config.index:
                choices = clusters.loc[column,k].set_index("medoid").loc[county,["state","county"]]
                if hasattr(choices,"to_frame"):
                    choices = choices.to_frame().T
                choices = [f"{y} {x}" for x,y in choices.values if f"{y} {x}" != county]
                config = best_config.loc[county].values.astype(int).tolist()[:-1]
                print("***",county,"***",flush=True)
                for choice in choices[:5]:
                    data = Total(*choice.rsplit(" ",1)[-1::-1])
                    X = data[exog]
                    y = data[column]
                    print(choice,"...",flush=True)
                    best,_,rmse = optimize(X,y,training,testing,limits,config)
                    print(choice,best,rmse,"***",flush=True)
