name: validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.9
    
    - name: Install packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Analyse code
      run: |
        pip install pylint
        cd loads
        pylint --fail-under 0 *.py

    - name: Run tests
      env:
        NSRDB_CREDENTIALS: ${{ secrets.NSRDB_CREDENTIALS }}
      run: |
        mkdir $HOME/.nsrdb
        echo "$NSRDB_CREDENTIALS" > $HOME/.nsrdb/credentials.json
        cd loads
        pip install ..
        python3 tests.py
